### ISSUE TITLE
Remove node_modules from repo

### ISSUE THREAD

**Issue by Mati365** [hatlesshacker/gitsie#4]

**Comment by hatlesshacker** [comment]
Quite frankly, rewriting code in place of all the node modules will be like re-inventing the wheel. But it'll surely be great to minimize the dependency on the modules :-D

**Comment by Mati365** [comment]
wtf, just delete node_modules/, all dev dependencies should be inside package.json

**Comment by carlosrrod** [comment]
You can create a file called `.gitignore` and add this to it: `node_modules`. Any file/directory you type into the `.gitignore` will be completely ignored by Git.

**Comment by hatlesshacker** [comment]
Contents inside `node_modules` are only edited when we add/remove modules. Thus, it'll change whenever `package.json` changes. There's no point in adding it to .gitignore.

Point is to minimize dependencies so as to increase the performance.

**Comment by carlosrrod** [comment]
I see, well the issue title says **Remove node_modules from repo** 
not
 **minimize dependencies so as to increase the performance** so I'm a bit confused, but alright! 👌

**Comment by Mati365** [comment]
@hatlesshacker What are you talking about? All information about your dependencies are inside package.json and lock and there isn't any point to store whole node_modules/ in your repository. Besides it you are not permitted to redistribute some of these packages in your repo due their license.

**Comment by Mati365** [comment]
@hatlesshacker FIXED

**Comment by hatlesshacker** [comment]
> there isn't any point to store whole node_modules/ in your repository

I just did a quick search, and got to know that this is actually true. Thanks for letting me know.

> you are not permitted to redistribute some of these packages in your repo due to their license

Sorry to hear that; I removed the directory
